[package]
name = "klystron"
version = "0.1.0"
authors = ["Masterchef365 <duncan.freeman1@gmail.com>"]
edition = "2018"

[dependencies]
erupt = "0.13.0"
winit = "0.22"
openxr = { version = "0.13.0", features = ["loaded"] }
nalgebra = "0.22"
bytemuck = "1.3.1"
anyhow = "1"
log = "0.4"
env_logger = "0.7"
drop_bomb = "0.1"
ctrlc = "3.1.5"
